name: Generate Snake Contribution Game

on:
  schedule:
    - cron: "0 0 * * *"  # tous les jours à minuit
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Vaidx0
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark&color_snake=#00ffff&color_dots=#1a1a1a,#2c3e50,#3498db,#2980b9,#1abc9c

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate GitHub contribution snake"
          add: "dist/*.svg"
